# Generated by Django 3.0.8 on 2021-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanksAPI', '0002_auto_20210127_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=255)),
                ('bank_id', models.IntegerField(max_length=20)),
                ('branch', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
