# Generated by Django 3.0.8 on 2021-02-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanksAPI', '0003_auto_20210127_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.IntegerField(),
        ),
    ]
